FROM golang:1.18-alpine3.16 AS builder

RUN apk -U --no-cache --upgrade --latest add build-base git gcc bash

WORKDIR /go/src/github.com/ory/hydra
RUN mkdir -p ./internal/httpclient
RUN mkdir -p ./internal/fosite

COPY go.mod go.sum ./
COPY internal/httpclient/go.* ./internal/httpclient
COPY internal/fosite/go.* ./internal/fosite

ENV GO111MODULE on
ENV CGO_ENABLED 1

RUN go mod download

COPY . .

RUN go build -tags sqlite,hsm,json1  -o /usr/bin/hydra

FROM alpine:3.16

RUN addgroup -S ory; \
    adduser -S ory -G ory -D -H -s /bin/nologin
RUN apk --no-cache --upgrade --latest add ca-certificates

COPY --from=builder /usr/bin/hydra /usr/bin/hydra

# set up nsswitch.conf for Go's "netgo" implementation
# - https://github.com/golang/go/blob/go1.9.1/src/net/conf.go#L194-L275
# RUN [ ! -e /etc/nsswitch.conf ] && echo 'hosts: files dns' > /etc/nsswitch.conf

# By creating the sqlite folder as the ory user, the mounted volume will be owned by ory:ory, which
# is required for read/write of SQLite.
RUN mkdir -p /var/lib/sqlite && \
    chown ory:ory /var/lib/sqlite

USER ory

ENTRYPOINT ["hydra"]
CMD ["serve", "all"]
