name: CI Tasks for Ory Hydra
on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:

# Cancel in-progress runs in current workflow.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  oidc-conformity:
    name: Run OIDC conformity tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: ory/ci/checkout@master
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: ~1.18
      - name: Start service
        run: ./test/conformance/start.sh
      - name: Run tests
        run: ./test/conformance/test.sh -v -short -parallel 16
        
  release:
    runs-on: ubuntu-latest
    steps:
      # Login to Docker
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      # Build docker images
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .docker/Dockerfile-alpine
          push: true
          tags: |
            ghcr.io/sb1finans/hydra:latest-alpine
            ghcr.io/sb1finans/hydra:${{ github.sha }}



